package db

import "github.com/toastsandwich/totality-assignment-GRPC-version/models"

var UserData = []*models.User{
	{
		ID:      1,
		FName:   "John",
		LName:   "Doe",
		City:    "New York",
		Phone:   1234567890,
		Height:  5.9,
		Married: true,
	},
	{
		ID:      2,
		FName:   "Jane",
		LName:   "Smith",
		City:    "Los Angeles",
		Phone:   2345678901,
		Height:  5.5,
		Married: false,
	},
	{
		ID:      3,
		FName:   "Alice",
		LName:   "Johnson",
		City:    "Chicago",
		Phone:   3456789012,
		Height:  5.7,
		Married: true,
	},
	{
		ID:      4,
		FName:   "Bob",
		LName:   "Brown",
		City:    "Houston",
		Phone:   4567890123,
		Height:  6.0,
		Married: false,
	},
	{
		ID:      5,
		FName:   "Milly",
		LName:   "Hudson",
		City:    "Boston",
		Phone:   3450127891,
		Height:  5.2,
		Married: true,
	},
	{
		ID:      6,
		FName:   "Michael",
		LName:   "Williams",
		City:    "New York",
		Phone:   5678901234,
		Height:  6.2,
		Married: false,
	},
	{
		ID:      7,
		FName:   "Emily",
		LName:   "Wang",
		City:    "Chicago",
		Phone:   6789012345,
		Height:  5.6,
		Married: true,
	},
	{
		ID:      8,
		FName:   "David",
		LName:   "Lee",
		City:    "Miami",
		Phone:   7890123456,
		Height:  5.11,
		Married: false,
	},
	{
		ID:      9,
		FName:   "Sophia",
		LName:   "Garcia",
		City:    "Dallas",
		Phone:   8901234567,
		Height:  5.4,
		Married: true,
	},
	{
		ID:      10,
		FName:   "James",
		LName:   "Martinez",
		City:    "Boston",
		Phone:   9012345678,
		Height:  5.8,
		Married: false,
	},
}
